### ISSUE TITLE
ERROR! Unexpected Exception, this is probably a bug: No module named 'distutils'

### ISSUE THREAD

**Issue by shixinlishixinli** [IntelAI/nauta#16]
hello 

i try to install nauta on centos7 ,but there is a bug : No module named 'distutils'. 
i can import distutils in python2 and python3 . i have no idea what should i do .

best
lisa shi

**Comment by pmilewsk** [comment]
Hello Lisa,

could you provide more logs for that? For me it seems that you have python miss-configured. Please also provide me python2 and python3 version.

Best Regards,
Piotr Milewski

**Comment by shixinlishixinli** [comment]
hi milewski
 the follow is the log.
2019-06-13 10:38:14,391 p=1524 u=lisas |  ERROR! Unexpected Exception, this is probably a bug: No module named 'distutils'
2019-06-13 10:38:14,391 p=1524 u=lisas |  to see the full traceback, use -vvv
2019-06-13 10:38:14,392 p=1524 u=lisas |  the full traceback was:

Traceback (most recent call last):
  File "ansible-playbook", line 118, in <module>
  File "/tmp/_MEIoLWl2d/ansible/cli/playbook.py", line 122, in run
    results = pbex.run()
  File "/tmp/_MEIoLWl2d/ansible/executor/playbook_executor.py", line 81, in run
    pb = Playbook.load(playbook_path, variable_manager=self._variable_manager, loader=self._loader)
  File "/tmp/_MEIoLWl2d/ansible/playbook/__init__.py", line 54, in load
    pb._load_playbook_data(file_name=file_name, variable_manager=variable_manager)
  File "/tmp/_MEIoLWl2d/ansible/playbook/__init__.py", line 106, in _load_playbook_data
    entry_obj = Play.load(entry, variable_manager=variable_manager, loader=self._loader, vars=vars)
  File "/tmp/_MEIoLWl2d/ansible/playbook/play.py", line 112, in load
    return p.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/tmp/_MEIoLWl2d/ansible/playbook/base.py", line 230, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/tmp/_MEIoLWl2d/ansible/playbook/play.py", line 197, in _load_roles
    roles.append(Role.load(ri, play=self))
  File "/tmp/_MEIoLWl2d/ansible/playbook/role/__init__.py", line 164, in load
    r._load_role_data(role_include, parent_role=parent_role)
  File "/tmp/_MEIoLWl2d/ansible/playbook/role/__init__.py", line 231, in _load_role_data
    self._task_blocks = load_list_of_blocks(task_data, play=self._play, role=self, loader=self._loader, variable_manager=self._variable_manager)
  File "/tmp/_MEIoLWl2d/ansible/playbook/helpers.py", line 80, in load_list_of_blocks
    loader=loader,
  File "/tmp/_MEIoLWl2d/ansible/playbook/block.py", line 93, in load
    return b.load_data(data, variable_manager=variable_manager, loader=loader)
  File "/tmp/_MEIoLWl2d/ansible/playbook/base.py", line 230, in load_data
    self._attributes[target_name] = method(name, ds[name])
  File "/tmp/_MEIoLWl2d/ansible/playbook/block.py", line 129, in _load_block
    use_handlers=self._use_handlers,
  File "/tmp/_MEIoLWl2d/ansible/playbook/helpers.py", line 125, in load_list_of_tasks
    (action, args, delegate_to) = args_parser.parse()
  File "/tmp/_MEIoLWl2d/ansible/parsing/mod_args.py", line 289, in parse
    if item in BUILTIN_TASKS or item in action_loader or item in module_loader:
  File "/tmp/_MEIoLWl2d/ansible/plugins/loader.py", line 341, in has_plugin
    return self.find_plugin(name) is not None
  File "/tmp/_MEIoLWl2d/ansible/plugins/loader.py", line 330, in find_plugin
  File "/tmp/_MEIoLWl2d/ansible/plugins/loader.py", line 330, in find_plugin
    plugin = self._find_plugin(name, mod_type=mod_type, ignore_deprecated=ignore_deprecated, check_aliases=check_aliases)
  File "/tmp/_MEIoLWl2d/ansible/plugins/loader.py", line 269, in _find_plugin
    for path in (p for p in self._get_paths() if p not in self._searched_paths and os.path.isdir(p)):
  File "/tmp/_MEIoLWl2d/ansible/plugins/loader.py", line 177, in _get_paths
    ret.extend(self._get_package_paths(subdirs=subdirs))
  File "/tmp/_MEIoLWl2d/ansible/plugins/loader.py", line 142, in _get_package_paths
    m = __import__(self.package)
  File "/tmp/_MEIoLWl2d/ansible/plugins/action/__init__.py", line 22, in <module>
    from ansible.executor.module_common import modify_module
  File "/tmp/_MEIoLWl2d/ansible/executor/module_common.py", line 33, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'



i can from distutils.version import LooseVersion in python 2.


best
lisa shi

**Comment by pmilewsk** [comment]
Hello Lisa,

Please be sure that you have installed distutils for python3 and python2 on deployment host:
https://github.com/IntelAI/nauta/blob/develop/docs/installation-and-configuration/Installer_System_Requirements/ISR.md#nauta-supported-operating-systems

I can offer you an online meeting to resolve all your issues next week (24.06 - 28.06) in your convenient time.

Best Regards,
Piotr Milewski

**Comment by pmilewsk** [comment]
Hi Lisa,

is this issue resolved or you need further assistance?

Best regards,
Piotr Milewski

**Comment by pmilewsk** [comment]
Hello,

This ticket will be closed in 5 days if there will not be any action from user.

Best Regards,
Piotr Milewski

**Comment by shixinlishixinli** [comment]
hi milewski

sorry for the late reply. i am sure i have installed the distutils for python . i have try to install nauta on docker images . but there are the same error. 

best
lisa shi

**Comment by pmilewsk** [comment]
Hi Lisa,

Do you need a meeting to resolve your issues? 
If yes - please send invitation with date on my e-mail at my github profile.

Remember that the packages need to be installed on Nauta hosts (or you need to provide proper repository for centos): 
https://github.com/IntelAI/nauta/blob/develop/docs/installation-and-configuration/Target_Host_Requirements/THR.md

Best Regards,
Piotr Milewski

**Comment by pmilewsk** [comment]
Issue was due to python and CentOS distutils package.
