### ISSUE TITLE
Failed to upload experiment

### ISSUE THREAD

**Issue by y-yas** [IntelAI/nauta#21]
hi,

An error occurred when running the Mnist sample after deploying nauta.
Could you teach me how to solve error?

```
[user01@centos7 nctl]$ nctl experiment submit -t tf-training-single examples/mnist_single_node.py --name single -v
INFO:util.dependencies_checker:Detected OS: centos 7
ERROR:util.cli_state:Dependency check failed.
Traceback (most recent call last):
  File "util/cli_state.py", line 82, in verify_cli_dependencies
  File "util/dependencies_checker.py", line 157, in check_os
util.exceptions.InvalidOsError: WARNING: This OS version (centos 7) is unsupported. Check the release notes for supported operating systems and proceed at your own risk.
Dependency check failed. Use -v or -vv option for more info.
Submitting experiments.
Experiment data directory: /home/user01/nctl/config/experiments/single already exists. It will be deleted to proceed with experiment submission. Do you want to continue? [y/N]: y
? Uploading experiment...INFO:util.kubectl:Port forwarding - proxy set up
? Uploading experiment...ERROR:util.system:COMMAND: ['git', 'ls-remote'] RESULT: Warning: Permanently added '[localhost]:56253' (ECDSA) to the list of known hosts.\nPermission denied (publickey).\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n
Traceback (most recent call last):
  File "util/system.py", line 182, in execute_system_command
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['git', 'ls-remote']' returned non-zero exit status 128.
ERROR:util.system:Warning: Permanently added '[localhost]:56253' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

ERROR:git_repo_manager.utils:Failed to upload experiment single to git repo manager.
Traceback (most recent call last):
  File "git_repo_manager/utils.py", line 102, in upload_experiment_to_git_repo_manager
  File "util/system.py", line 121, in __call__
RuntimeError: Failed to execute command: ['git', 'ls-remote']
WARNING:retry.api:Failed to execute command: ['git', 'ls-remote'], retrying in 1 seconds...
? Uploading experiment...INFO:util.kubectl:Port forwarding - proxy set up
? Uploading experiment...ERROR:util.system:COMMAND: ['git', 'ls-remote'] RESULT: Warning: Permanently added '[localhost]:30372' (ECDSA) to the list of known hosts.\nPermission denied (publickey).\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n
Traceback (most recent call last):
  File "util/system.py", line 182, in execute_system_command
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['git', 'ls-remote']' returned non-zero exit status 128.
ERROR:util.system:Warning: Permanently added '[localhost]:30372' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

ERROR:git_repo_manager.utils:Failed to upload experiment single to git repo manager.
Traceback (most recent call last):
  File "git_repo_manager/utils.py", line 102, in upload_experiment_to_git_repo_manager
  File "util/system.py", line 121, in __call__
RuntimeError: Failed to execute command: ['git', 'ls-remote']
WARNING:retry.api:Failed to execute command: ['git', 'ls-remote'], retrying in 1 seconds...
? Uploading experiment...INFO:util.kubectl:Port forwarding - proxy set up
? Uploading experiment...ERROR:util.system:COMMAND: ['git', 'ls-remote'] RESULT: Warning: Permanently added '[localhost]:25259' (ECDSA) to the list of known hosts.\nPermission denied (publickey).\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n
Traceback (most recent call last):
  File "util/system.py", line 182, in execute_system_command
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['git', 'ls-remote']' returned non-zero exit status 128.
ERROR:util.system:Warning: Permanently added '[localhost]:25259' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

ERROR:git_repo_manager.utils:Failed to upload experiment single to git repo manager.
Traceback (most recent call last):
  File "git_repo_manager/utils.py", line 102, in upload_experiment_to_git_repo_manager
  File "util/system.py", line 121, in __call__
RuntimeError: Failed to execute command: ['git', 'ls-remote']
WARNING:retry.api:Failed to execute command: ['git', 'ls-remote'], retrying in 1 seconds...
? Uploading experiment...INFO:util.kubectl:Port forwarding - proxy set up
? Uploading experiment...ERROR:util.system:COMMAND: ['git', 'ls-remote'] RESULT: Warning: Permanently added '[localhost]:16217' (ECDSA) to the list of known hosts.\nPermission denied (publickey).\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n
Traceback (most recent call last):
  File "util/system.py", line 182, in execute_system_command
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['git', 'ls-remote']' returned non-zero exit status 128.
ERROR:util.system:Warning: Permanently added '[localhost]:16217' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

? Uploading experiment...ERROR:git_repo_manager.utils:Failed to upload experiment single to git repo manager.
Traceback (most recent call last):
  File "git_repo_manager/utils.py", line 102, in upload_experiment_to_git_repo_manager
  File "util/system.py", line 121, in __call__
RuntimeError: Failed to execute command: ['git', 'ls-remote']
WARNING:retry.api:Failed to execute command: ['git', 'ls-remote'], retrying in 1 seconds...
? Uploading experiment...INFO:util.kubectl:Port forwarding - proxy set up
? Uploading experiment...ERROR:util.system:COMMAND: ['git', 'ls-remote'] RESULT: Warning: Permanently added '[localhost]:51135' (ECDSA) to the list of known hosts.\nPermission denied (publickey).\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n
Traceback (most recent call last):
  File "util/system.py", line 182, in execute_system_command
  File "subprocess.py", line 356, in check_output
  File "subprocess.py", line 438, in run
subprocess.CalledProcessError: Command '['git', 'ls-remote']' returned non-zero exit status 128.
ERROR:util.system:Warning: Permanently added '[localhost]:51135' (ECDSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

ERROR:git_repo_manager.utils:Failed to upload experiment single to git repo manager.
Traceback (most recent call last):
  File "git_repo_manager/utils.py", line 102, in upload_experiment_to_git_repo_manager
  File "util/system.py", line 121, in __call__
RuntimeError: Failed to execute command: ['git', 'ls-remote']
? Uploading experiment...ERROR:commands.experiment.common:Failed to upload experiment.
Traceback (most recent call last):
  File "commands/experiment/common.py", line 377, in submit_experiment
  File "</home/user01/nctl/nctl-cli/decorator.pyc:decorator-gen-4>", line 2, in upload_experiment_to_git_repo_manager
  File "retry/api.py", line 74, in retry_decorator
  File "retry/api.py", line 33, in __retry_internal
  File "git_repo_manager/utils.py", line 102, in upload_experiment_to_git_repo_manager
  File "util/system.py", line 121, in __call__
RuntimeError: Failed to execute command: ['git', 'ls-remote']
Problems during submitting experiment: Failed to upload experiment.
```

thanks,
yas

**Comment by mateusz-ciesielski** [comment]
Hi yas,
something went wrong with `nctl`-> nauta's git communication, in order to find out why, please try following steps:
1. Check git version, just in case:
```
git --version
```
2. Then enable debug git output:
```
export GIT_TRACE=2
export GIT_CURL_VERBOSE=1
```
3. Finally, enable debug ssh output:

3.1 Find where Nauta's SSH script resides (we use such script in order to be compatible with Git than 2.0):
```
ls -la /home/user01/nctl/config/ | grep ssh-<name of your user>
```
- name of script that we want to modify will be in the output, please post content of this file.
It should look similar to this one:
```
ssh -i /Users/mciesiel/Documents/Repos/nauta/applications/cli/dist/config/.ssh-key-bingo-a20f3498d4da48f0fd5a65ffae191d43 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $*
```

3.2 Open SSH script file with vim, or some other editor and add `-vvv` after `ssh` word, e.g. change:
```
`ssh -i <key path> ...
```
to:
```
ssh -vvv -i <key path>
```

After these steps, please run submit again and post output here.

Thanks,
Mateusz

**Comment by y-yas** [comment]
hi, Mateusz

Thank you again for your reply.

I ran the command I told you, but the results don't seem to change.


```
[user01@centos7 nctl]$ git --version
git version 1.8.3.1
```

debug git output:
```
[user01@centos7 nctl]$ ls -la /home/user01/nctl/config/ | grep ssh-user01
-r-x------  1 user01 user01      143 10月 22 15:10 ssh-user01-1a5d7a2bcd738717e72c915999fc1af4

[user01@centos7 nctl]$ cat /home/user01/nctl/config/ssh-user01-1a5d7a2bcd738717e72c915999fc1af4
ssh -i /home/user01/nctl/config/.ssh-key-user01-1a5d7a2bcd738717e72c915999fc1af4 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $*[user01@centos7 nctl]$
```



```
[user01@centos7 ~]$ cat nctl/config/ssh-user01-1a5d7a2bcd738717e72c915999fc1af4
ssh -vvv -i /home/user01/nctl/config/.ssh-key-user01-1a5d7a2bcd738717e72c915999fc1af4 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $*

[user01@centos7 nctl]$ nctl experiment submit -t tf-training-single examples/mnist_single_node.py --name single
Dependency check failed. Use -v or -vv option for more info.
Submitting experiments.
Experiment data directory: /home/user01/nctl/config/experiments/single already exists. It will be deleted to proceed with experiment submission. Do you want to continue? [y/N]: y
Problems during submitting experiment: Failed to upload experiment.
[user01@centos7 nctl]$
```



I was able to submit a problem with the server that I introduced last time, but if I redeployed it last weekend, I couldn't connect.


thanks,
yas

**Comment by y-yas** [comment]
hi,
Deploying another Nauta cluster was successful. The status remains QUEUED ...

```
[user02@centos7 nctl]$ nctl experiment submit -t tf-training-single examples/mnist_single_node.py --name single
Dependency check failed. Use -v or -vv option for more info.
Submitting experiments.
| Name   | Parameters           | Status   | Message   |
|--------+----------------------+----------+-----------|
| single | mnist_single_node.py | QUEUED   |           |
```

Master resources remain the same, but less worker resources.
Node 4Node⇒2Node
CPU 16Core⇒8Core
Memory 16GB⇒16GB　※memory is not reduce.

Is it relevant to change the resource?
Should I increase the resources of the master when I increase the resources of the worker?

thanks,
yas

**Comment by mzylowski** [comment]
Hello yas,

You can get pod list (there should be pod for your experiment in 'pending' state) by `kubectl get po`
You can describe queued pod by 
```kubectl describe po [pod-name-copied-from-above-output]```
You probably should see some messages about lack of resources.

Also by `nctl verify` you can check your config settings. Probably you will see something like 
```The following packs have incorrect resources' settings. Use the 'config' command to align those settings with resources available on a cluster.```

If this is your case you should trigger `nctl config` command to scale templates to your resources on the cluster. Minimal values that can be passed through this command is 4 cores and 8Gi. You can run: ```nctl config -c 4 -m 8Gi```. 

After `config` command you should schedule experiment again by `nctl submit`. 

Please note, your single experiment never be scheduled, so you probably want cancel this experiment by
```nctl experiment cancel single```.

Thanks,
Michal

**Comment by y-yas** [comment]
hi, Michal

thank you for youre reply
there was a POD that was PENDING, exp started when I set resources with nctl config.

```
$nctl exp list
Dependency check failed. Use -v or -vv option for more info.
| Name     | Parameters           | Metrics   | Submission date        | Start date             | Duration    | Owner   | Status    | Template name      | Template version   |
|----------+----------------------+-----------+------------------------+------------------------+-------------+---------+-----------+--------------------+--------------------|
| single   | mnist_single_node.py |           | 2019-10-25 04:54:43 PM |                        |             | user02  | CANCELLED | tf-training-single | 0.1.0              |
| single-2 | mnist_single_node.py |           | 2019-10-25 04:58:15 PM | 2019-10-25 04:58:44 PM | 0d 0h 0m 1s | user02  | RUNNING   | tf-training-single | 0.1.0              |
```

thanks,
yas

**Comment by y-yas** [comment]
hi, Mateusz


The environment I deployed was a demo environment, so I deployed several times, but when I deleted the nauta user with `nctl user delete` on the client side and recreated the user with OS `userdel`, the experiment was submitted I did it.

If an error occurs in the upload of exp, it seems better to delete the user on the OS side.


thanks,
yas

**Comment by y-yas** [comment]
hi, 

After rebuilding nauta, exp can no longer be uploaded. . .
Last time it was solved by rebuilding, but this time it does not seem to work even if rebuilding.

Can you give me a solution?


```
[user01@console nauta]$ nctl experiment submit -t tf-training-single examples/mnist_single_node.py --name=single
Dependency check failed. Use -v or -vv option for more info.
Submitting experiments.
Problems during submitting experiment: Failed to upload experiment.
```

Git ver:
`[user01@console ~]$ git --version
git version 1.8.3.1
`

debug git output:
see attach.
[submit_exp.txt](https://github.com/IntelAI/nauta/files/4044052/submit_exp.txt)



thanks,
yas
