### ISSUE TITLE
status of horovod experiment is QUEUED.

### ISSUE THREAD

**Issue by y-yas** [IntelAI/nauta#22]
hi,

I am running the experiment of the sample, but I can run it on a single node, but in multi node and horovod the status remains QUEUED.
Could you tell me how to run horovod?

```
[user01@console nauta]$ nctl experiment submit -t tf-training-horovod examples/mnist_horovod.py -v
INFO:util.dependencies_checker:Detected OS: centos 7
ERROR:util.cli_state:Dependency check failed.
Traceback (most recent call last):
  File "util/cli_state.py", line 82, in verify_cli_dependencies
  File "util/dependencies_checker.py", line 157, in check_os
util.exceptions.InvalidOsError: WARNING: This OS version (centos 7) is unsupported. Check the release notes for supported operating systems and proceed at your own risk.
Dependency check failed. Use -v or -vv option for more info.
Submitting experiments.
Experiment data directory: /home/user01/nauta/config/experiments/horovod-4 already exists. It will be deleted to proceed with experiment submission. Do you want to continue? [y/N]: y
? Uploading experiment...INFO:util.kubectl:Port forwarding - proxy set up
? Building experiment image...INFO:platform_resources.workflow:Waiting for workflow horovod-4-image-build-7btht to complete. Attempt #0
? Building experiment image...INFO:platform_resources.workflow:Waiting for workflow horovod-4-image-build-7btht to complete. Attempt #1
? Building experiment image...INFO:platform_resources.workflow:Waiting for workflow horovod-4-image-build-7btht to complete. Attempt #2
? Building experiment image...INFO:platform_resources.workflow:Waiting for workflow horovod-4-image-build-7btht to complete. Attempt #3
? Building experiment image...INFO:platform_resources.workflow:Waiting for workflow horovod-4-image-build-7btht to complete. Attempt #4
? Building experiment image...INFO:platform_resources.workflow:Waiting for workflow horovod-4-image-build-7btht to complete. Attempt #5
? Building experiment image...INFO:platform_resources.workflow:Waiting for workflow horovod-4-image-build-7btht to complete. Attempt #6
? Building experiment image...INFO:platform_resources.workflow:Waiting for workflow horovod-4-image-build-7btht to complete. Attempt #7
? Building experiment image...INFO:platform_resources.workflow:Waiting for workflow horovod-4-image-build-7btht to complete. Attempt #8
| Name      | Parameters       | Status   | Message   |
|-----------+------------------+----------+-----------|
| horovod-4 | mnist_horovod.py | QUEUED   |           |

```

```
[user01@console nauta]$ nctl exp list
Dependency check failed. Use -v or -vv option for more info.
| Name      | Parameters           | Metrics                     | Submission date        | Start date             | Duration     | Owner   | Status    | Template name       | Template version   |
|-----------+----------------------+-----------------------------+------------------------+------------------------+--------------+---------+-----------+---------------------+--------------------|
| horovod   | mnist_horovod.py     |                             | 2019-11-06 02:12:25 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-2 | mnist_horovod.py     |                             | 2019-11-06 02:16:13 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-3 | mnist_horovod.py     |                             | 2019-11-06 02:19:40 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-4 | mnist_horovod.py     |                             | 2019-11-06 02:21:17 PM |                        |              | user01  | QUEUED    | tf-training-horovod | 0.2.2              |
| multinode | mnist_multinode.py   |                             | 2019-11-06 02:25:31 PM |                        |              | user01  | QUEUED    | tf-training-multi   | 0.1.0              |
| single    | mnist_single_node.py | accuracy: 0.96875           | 2019-11-06 02:08:11 PM | 2019-11-06 02:08:47 PM | 0d 0h 0m 36s | user01  | COMPLETE  | tf-training-single  | 0.1.0              |
|           |                      | global_step: 499            |                        |                        |              |         |           |                     |                    |
|           |                      | loss: 0.080687426           |                        |                        |              |         |           |                     |                    |
|           |                      | validation_accuracy: 0.9814 |                        |                        |              |         |           |                     |                    |
[user01@console nauta]$

```

```
[user01@console nauta]$ kubectl get node
NAME                            STATUS   ROLES    AGE   VERSION
nauta-master.node.ai-ex.local   Ready    Master   65m   v1.15.3
worker01.node.ai-ex.local       Ready    Worker   65m   v1.15.3
worker02.node.ai-ex.local       Ready    Worker   65m   v1.15.3
worker03.node.ai-ex.local       Ready    Worker   65m   v1.15.3
worker04.node.ai-ex.local       Ready    Worker   65m   v1.15.3
[user01@console nauta]$
```

thanks,
yas

**Comment by mzylowski** [comment]
Hello, yas!

This seems like another issue related with resources.
I see `multinode` and `horovod-4` experiments on the list with QUEUED state.
I believe we should cancel `multinode` for now, because maybe some containers related with `multinode` are partially scheduled and some resources are used for them.

Please attach output of `nctl experiment view` command for `horovod-4`. In this output some hints about resources problem can appear.

You can also try run `nctl config` command with some low numbers of CPU and memory.

Also You can try to schedule horovod experiment by giving resources explicitly:
```
nctl exp submit ... -p cpus 2 -p processesPerNode 1 -p cpu 2 -p memory 8Gi
``` 

Regards,
Michal

**Comment by y-yas** [comment]
hi, Michal

thank you for your reply.

Before running multinode exp, horovod was executed, but Status was QUEUED.

I tried changing resources with nctl config, but the status remained QUEUED, so when I executed it with the -p option, exp started but the status became FAIL.


```
[user01@console nauta]$ nctl experiment submit -t tf-training-horovod examples/mnist_horovod.py -p cpus 2 -p processesPerNode 1 -p cpu 2 -p memory 8Gi
```


I tried changing some of the CPUs and CPU values ​​for -p, but all of them failed.

```
[user01@console nauta]$ nctl exp list
Dependency check failed. Use -v or -vv option for more info.
| Name        | Parameters           | Metrics                     | Submission date        | Start date             | Duration     | Owner   | Status    | Template name       | Template version   |
|-------------+----------------------+-----------------------------+------------------------+------------------------+--------------+---------+-----------+---------------------+--------------------|
| horovod     | mnist_horovod.py     |                             | 2019-11-06 02:12:25 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-10  | mnist_horovod.py     |                             | 2019-11-07 10:27:55 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-11  | mnist_horovod.py     |                             | 2019-11-07 11:03:57 AM | 2019-11-07 11:04:09 AM | 0d 0h 0m 6s  | user01  | FAILED    | tf-training-horovod | 0.2.2              |
| horovod-12  | mnist_horovod.py     |                             | 2019-11-07 11:05:43 AM | 2019-11-07 11:05:57 AM | 0d 0h 0m 1s  | user01  | FAILED    | tf-training-horovod | 0.2.2              |
| horovod-13  | mnist_horovod.py     |                             | 2019-11-07 11:07:45 AM | 2019-11-07 11:07:57 AM | 0d 0h 0m 5s  | user01  | FAILED    | tf-training-horovod | 0.2.2              |
| horovod-14  | mnist_horovod.py     |                             | 2019-11-07 11:10:03 AM | 2019-11-07 11:10:11 AM | 0d 0h 0m 5s  | user01  | FAILED    | tf-training-horovod | 0.2.2              |
| horovod-15  | mnist_horovod.py     |                             | 2019-11-07 11:14:06 AM | 2019-11-07 11:14:14 AM | 0d 0h 0m 5s  | user01  | FAILED    | tf-training-horovod | 0.2.2              |
| horovod-2   | mnist_horovod.py     |                             | 2019-11-06 02:16:13 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-3   | mnist_horovod.py     |                             | 2019-11-06 02:19:40 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-4   | mnist_horovod.py     |                             | 2019-11-06 02:21:17 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-5   | mnist_horovod.py     |                             | 2019-11-07 10:06:31 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-6   | mnist_horovod.py     |                             | 2019-11-07 10:08:05 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-7   | mnist_horovod.py     |                             | 2019-11-07 10:09:13 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-8   | mnist_horovod.py     |                             | 2019-11-07 10:12:52 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-9   | mnist_horovod.py     |                             | 2019-11-07 10:15:47 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| multinode   | mnist_multinode.py   |                             | 2019-11-06 02:25:31 PM |                        |              | user01  | CANCELLED | tf-training-multi   | 0.1.0              |
| multinode-2 | mnist_multinode.py   |                             | 2019-11-07 11:00:15 AM | 2019-11-07 11:00:23 AM | 0d 0h 1m 50s | user01  | COMPLETE  | tf-training-multi   | 0.1.0              |
| single      | mnist_single_node.py | accuracy: 0.96875           | 2019-11-06 02:08:11 PM | 2019-11-06 02:08:47 PM | 0d 0h 0m 36s | user01  | COMPLETE  | tf-training-single  | 0.1.0              |
|             |                      | global_step: 499            |                        |                        |              |         |           |                     |                    |
|             |                      | loss: 0.080687426           |                        |                        |              |         |           |                     |                    |
|             |                      | validation_accuracy: 0.9814 |                        |                        |              |         |           |                     |                    |
| single-2    | mnist_single_node.py |                             | 2019-11-07 10:29:28 AM |                        |              | user01  | CANCELLED | tf-training-single  | 0.1.0              |
| single-3    | mnist_single_node.py |                             | 2019-11-07 10:30:58 AM |                        |              | user01  | CANCELLED | tf-training-single  | 0.1.0              |
| single-4    | mnist_single_node.py |                             | 2019-11-07 10:32:36 AM | 2019-11-07 10:32:50 AM |              | user01  | FAILED    | tf-training-single  | 0.1.0              |
| single-5    | mnist_single_node.py |                             | 2019-11-07 10:33:42 AM | 2019-11-07 10:33:46 AM |              | user01  | FAILED    | tf-training-single  | 0.1.0              |
| single-6    | mnist_single_node.py | accuracy: 0.984375          | 2019-11-07 10:57:39 AM | 2019-11-07 10:57:53 AM | 0d 0h 0m 34s | user01  | COMPLETE  | tf-training-single  | 0.1.0              |
|             |                      | global_step: 499            |                        |                        |              |         |           |                     |                    |
|             |                      | loss: 0.05520958            |                        |                        |              |         |           |                     |                    |
|             |                      | validation_accuracy: 0.9846 |                        |                        |              |         |           |                     |                    |
[user01@console nauta]$
```

```
[user01@console nauta]$ nctl exp view horovod-15
Dependency check failed. Use -v or -vv option for more info.
| Name       | Parameters       | Metrics   | Submission date        | Start date             | Duration    | Owner   | Status   | Template name       | Template version   |
|------------+------------------+-----------+------------------------+------------------------+-------------+---------+----------+---------------------+--------------------|
| horovod-15 | mnist_horovod.py |           | 2019-11-07 11:14:06 AM | 2019-11-07 11:14:14 AM | 0d 0h 0m 5s | user01  | FAILED   | tf-training-horovod | 0.2.2              |

Pods participating in the execution:

| Name                 | Uid             | Pod Conditions                    | Container Details                                     |
|----------------------+-----------------+-----------------------------------+-------------------------------------------------------|
| horovod-15-hvd-0     | a2c662d5-7872-4 | Initialized: True                 | - Name: worker                                        |
|                      | 69a-93ee-405754 |                                   | - Status: Running, started at: 2019-11-07 11:14:08 AM |
|                      | 841adf          | Ready: True                       | - Volumes:                                            |
|                      |                 |                                   |   horovod-15-hvd-cm <rw> @ /horovod/generated         |
|                      |                 | ContainersReady: True             |   input-home <ro> @ /mnt/input/home                   |
|                      |                 |                                   |   input-public <ro> @ /mnt/input/root                 |
|                      |                 | PodScheduled: True                |   output-home <rw> @ /mnt/output/home                 |
|                      |                 |                                   |   output-public <ro> @ /mnt/output/root               |
|                      |                 |                                   |   output-public <rw> @ /mnt/output/root/public        |
|                      |                 |                                   |   input-public <rw> @ /mnt/input/root/public          |
|                      |                 |                                   |   output-home <rw> @ /mnt/output/experiment           |
|                      |                 |                                   |   default-token-gth99 <ro> @                          |
|                      |                 |                                   |     /var/run/secrets/kubernetes.io/serviceaccount     |
|                      |                 |                                   |                                                       |
|                      |                 |                                   | - Resources:                                          |
|                      |                 |                                   |   - Requests:                                         |
|                      |                 |                                   |     cpu: 4000m    memory: 8GiB                        |
|                      |                 |                                   |   - Limits:                                           |
|                      |                 |                                   |     cpu: 4000m    memory: 8GiB                        |
| horovod-15-hvd-1     | 7e8e88e8-59e5-4 | Initialized: True                 | - Name: worker                                        |
|                      | 92a-beb6-639534 |                                   | - Status: Running, started at: 2019-11-07 11:14:08 AM |
|                      | 0e16ab          | Ready: True                       | - Volumes:                                            |
|                      |                 |                                   |   horovod-15-hvd-cm <rw> @ /horovod/generated         |
|                      |                 | ContainersReady: True             |   input-home <ro> @ /mnt/input/home                   |
|                      |                 |                                   |   input-public <ro> @ /mnt/input/root                 |
|                      |                 | PodScheduled: True                |   output-home <rw> @ /mnt/output/home                 |
|                      |                 |                                   |   output-public <ro> @ /mnt/output/root               |
|                      |                 |                                   |   output-public <rw> @ /mnt/output/root/public        |
|                      |                 |                                   |   input-public <rw> @ /mnt/input/root/public          |
|                      |                 |                                   |   output-home <rw> @ /mnt/output/experiment           |
|                      |                 |                                   |   default-token-gth99 <ro> @                          |
|                      |                 |                                   |     /var/run/secrets/kubernetes.io/serviceaccount     |
|                      |                 |                                   |                                                       |
|                      |                 |                                   | - Resources:                                          |
|                      |                 |                                   |   - Requests:                                         |
|                      |                 |                                   |     cpu: 4000m    memory: 8GiB                        |
|                      |                 |                                   |   - Limits:                                           |
|                      |                 |                                   |     cpu: 4000m    memory: 8GiB                        |
| horovod-15-hvd-2     | d4e95c5f-f404-4 | Initialized: True                 | - Name: worker                                        |
|                      | a77-b5d2-09cff1 |                                   | - Status: Running, started at: 2019-11-07 11:14:08 AM |
|                      | b08919          | Ready: True                       | - Volumes:                                            |
|                      |                 |                                   |   horovod-15-hvd-cm <rw> @ /horovod/generated         |
|                      |                 | ContainersReady: True             |   input-home <ro> @ /mnt/input/home                   |
|                      |                 |                                   |   input-public <ro> @ /mnt/input/root                 |
|                      |                 | PodScheduled: True                |   output-home <rw> @ /mnt/output/home                 |
|                      |                 |                                   |   output-public <ro> @ /mnt/output/root               |
|                      |                 |                                   |   output-public <rw> @ /mnt/output/root/public        |
|                      |                 |                                   |   input-public <rw> @ /mnt/input/root/public          |
|                      |                 |                                   |   output-home <rw> @ /mnt/output/experiment           |
|                      |                 |                                   |   default-token-gth99 <ro> @                          |
|                      |                 |                                   |     /var/run/secrets/kubernetes.io/serviceaccount     |
|                      |                 |                                   |                                                       |
|                      |                 |                                   | - Resources:                                          |
|                      |                 |                                   |   - Requests:                                         |
|                      |                 |                                   |     cpu: 4000m    memory: 8GiB                        |
|                      |                 |                                   |   - Limits:                                           |
|                      |                 |                                   |     cpu: 4000m    memory: 8GiB                        |
| horovod-15-hvd-v425b | bbe417d5-1375-4 | Initialized: True                 | - Name: horovod-master                                |
|                      | b3c-ac4f-34cdc0 |                                   | - Status: Terminated, Error                           |
|                      | 5bb137          | Ready: False                      | - Volumes:                                            |
|                      |                 |  reason: ContainersNotReady,      |   shared-data <rw> @ /horovod/init                    |
|                      |                 |  message: containers with unready |   horovod-15-hvd-cm <rw> @ /horovod/generated         |
|                      |                 |   status: [horovod-master         |   input-home <ro> @ /mnt/input/home                   |
|                      |                 |   kubectl]                        |   input-public <ro> @ /mnt/input/root                 |
|                      |                 | ContainersReady: False            |   output-home <rw> @ /mnt/output/home                 |
|                      |                 |  reason: ContainersNotReady,      |   output-public <ro> @ /mnt/output/root               |
|                      |                 |  message: containers with unready |   output-public <rw> @ /mnt/output/root/public        |
|                      |                 |   status: [horovod-master         |   input-public <rw> @ /mnt/input/root/public          |
|                      |                 |   kubectl]                        |   output-home <rw> @ /mnt/output/experiment           |
|                      |                 | PodScheduled: True                |   default-token-gth99 <ro> @                          |
|                      |                 |                                   |     /var/run/secrets/kubernetes.io/serviceaccount     |
|                      |                 |                                   |                                                       |
|                      |                 |                                   | - Resources:                                          |
|                      |                 |                                   |   - Requests:                                         |
|                      |                 |                                   |     cpu: 4000m    memory: 8GiB                        |
|                      |                 |                                   |   - Limits:                                           |
|                      |                 |                                   |     cpu: 4000m    memory: 8GiB                        |
|                      |                 |                                   | - Name: kubectl                                       |
|                      |                 |                                   | - Status: Terminated, Completed                       |
|                      |                 |                                   | - Volumes:                                            |
|                      |                 |                                   |   shared-data <rw> @ /horovod/init                    |
|                      |                 |                                   |   horovod-15-hvd-cm <rw> @ /horovod/generated         |
|                      |                 |                                   |   default-token-gth99 <ro> @                          |
|                      |                 |                                   |     /var/run/secrets/kubernetes.io/serviceaccount     |
|                      |                 |                                   |                                                       |
|                      |                 |                                   | - Resources:                                          |

Resources used by pods:

| Resource type    | Total usage   |
|------------------+---------------|
| CPU requests:    | 16000m        |
| Memory requests: | 32GiB         |
| CPU limits:      | 16000m        |
| Memory limits:   | 32GiB         |
[user01@console nauta]$
```



thanks,
Yas

**Comment by y-yas** [comment]
hi, Michal

When  `kubectl get pod`  was executed, horodod's POD was FAIL.


[https://github.com/IntelAI/nauta/blob/develop/docs/installation-and-configuration/Troubleshooting/T.md#a-multinode-horovod-experiment-receives-a-failed-status](url)



thanks,
yas

**Comment by mzylowski** [comment]
hello, yas
Can you post pod logs to be sure about this case?

thanks,
Michal

**Comment by y-yas** [comment]
hi, Michal

Today, the same sample exp was successful.
The environment has not changed since the previous time. . .
If a FAIL occurs, post a log.


```
[user01@console nauta]$ nctl exp list
Dependency check failed. Use -v or -vv option for more info.
| Name                             | Parameters           | Metrics                     | Submission date        | Start date             | Duration     | Owner   | Status    | Template name       | Template version   |
|----------------------------------+----------------------+-----------------------------+------------------------+------------------------+--------------+---------+-----------+---------------------+--------------------|
| horovod                          | mnist_horovod.py     |                             | 2019-11-06 02:12:25 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-10                       | mnist_horovod.py     |                             | 2019-11-07 10:27:55 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-11                       | mnist_horovod.py     |                             | 2019-11-07 11:03:57 AM | 2019-11-07 11:04:09 AM | 0d 0h 0m 6s  | user01  | FAILED    | tf-training-horovod | 0.2.2              |
| horovod-12                       | mnist_horovod.py     |                             | 2019-11-07 11:05:43 AM | 2019-11-07 11:05:57 AM | 0d 0h 0m 1s  | user01  | FAILED    | tf-training-horovod | 0.2.2              |
| horovod-13                       | mnist_horovod.py     |                             | 2019-11-07 11:07:45 AM | 2019-11-07 11:07:57 AM | 0d 0h 0m 5s  | user01  | FAILED    | tf-training-horovod | 0.2.2              |
| horovod-14                       | mnist_horovod.py     |                             | 2019-11-07 11:10:03 AM | 2019-11-07 11:10:11 AM | 0d 0h 0m 5s  | user01  | FAILED    | tf-training-horovod | 0.2.2              |
| horovod-15                       | mnist_horovod.py     |                             | 2019-11-07 11:14:06 AM | 2019-11-07 11:14:14 AM | 0d 0h 0m 5s  | user01  | FAILED    | tf-training-horovod | 0.2.2              |
| horovod-16                       | mnist_horovod.py     | accuracy: 0.328125          | 2019-11-13 09:26:50 AM | 2019-11-13 09:27:00 AM | 0d 0h 0m 35s | user01  | COMPLETE  | tf-training-horovod | 0.2.2              |
|                                  |                      | global_step: 37             |                        |                        |              |         |           |                     |                    |
|                                  |                      | loss: 2.113782              |                        |                        |              |         |           |                     |                    |
| horovod-17                       | mnist_horovod.py     | accuracy: 0.578125          | 2019-11-13 09:28:55 AM | 2019-11-13 09:29:05 AM | 0d 0h 0m 35s | user01  | COMPLETE  | tf-training-horovod | 0.2.2              |
|                                  |                      | global_step: 37             |                        |                        |              |         |           |                     |                    |
|                                  |                      | loss: 1.9744525             |                        |                        |              |         |           |                     |                    |
| horovod-2                        | mnist_horovod.py     |                             | 2019-11-06 02:16:13 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-3                        | mnist_horovod.py     |                             | 2019-11-06 02:19:40 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-4                        | mnist_horovod.py     |                             | 2019-11-06 02:21:17 PM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-5                        | mnist_horovod.py     |                             | 2019-11-07 10:06:31 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-6                        | mnist_horovod.py     |                             | 2019-11-07 10:08:05 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-7                        | mnist_horovod.py     |                             | 2019-11-07 10:09:13 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-8                        | mnist_horovod.py     |                             | 2019-11-07 10:12:52 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| horovod-9                        | mnist_horovod.py     |                             | 2019-11-07 10:15:47 AM |                        |              | user01  | CANCELLED | tf-training-horovod | 0.2.2              |
| mnist-tens-647-19-11-08-09-41-21 | mnist_tensorboard.py |                             | 2019-11-08 09:41:48 AM | 2019-11-08 09:41:56 AM | 0d 0h 0m 57s | user01  | COMPLETE  | tf-training-multi   | 0.1.0              |
| multinode                        | mnist_multinode.py   |                             | 2019-11-06 02:25:31 PM |                        |              | user01  | CANCELLED | tf-training-multi   | 0.1.0              |
| multinode-2                      | mnist_multinode.py   |                             | 2019-11-07 11:00:15 AM | 2019-11-07 11:00:23 AM | 0d 0h 1m 50s | user01  | COMPLETE  | tf-training-multi   | 0.1.0              |
| multinode-3                      | mnist_multinode.py   |                             | 2019-11-08 09:36:15 AM | 2019-11-08 09:36:24 AM | 0d 0h 1m 53s | user01  | COMPLETE  | tf-training-multi   | 0.1.0              |
| single                           | mnist_single_node.py | accuracy: 0.96875           | 2019-11-06 02:08:11 PM | 2019-11-06 02:08:47 PM | 0d 0h 0m 36s | user01  | COMPLETE  | tf-training-single  | 0.1.0              |
|                                  |                      | global_step: 499            |                        |                        |              |         |           |                     |                    |
|                                  |                      | loss: 0.080687426           |                        |                        |              |         |           |                     |                    |
|                                  |                      | validation_accuracy: 0.9814 |                        |                        |              |         |           |                     |                    |
| single-2                         | mnist_single_node.py |                             | 2019-11-07 10:29:28 AM |                        |              | user01  | CANCELLED | tf-training-single  | 0.1.0              |
| single-3                         | mnist_single_node.py |                             | 2019-11-07 10:30:58 AM |                        |              | user01  | CANCELLED | tf-training-single  | 0.1.0              |
| single-4                         | mnist_single_node.py |                             | 2019-11-07 10:32:36 AM | 2019-11-07 10:32:50 AM |              | user01  | FAILED    | tf-training-single  | 0.1.0              |
| single-5                         | mnist_single_node.py |                             | 2019-11-07 10:33:42 AM | 2019-11-07 10:33:46 AM |              | user01  | FAILED    | tf-training-single  | 0.1.0              |
| single-6                         | mnist_single_node.py | accuracy: 0.984375          | 2019-11-07 10:57:39 AM | 2019-11-07 10:57:53 AM | 0d 0h 0m 34s | user01  | COMPLETE  | tf-training-single  | 0.1.0              |
|                                  |                      | global_step: 499            |                        |                        |              |         |           |                     |                    |
|                                  |                      | loss: 0.05520958            |                        |                        |              |         |           |                     |                    |
|                                  |                      | validation_accuracy: 0.9846 |                        |                        |              |         |           |                     |                    |
[user01@console nauta]$
```


thanks,
yas
