### ISSUE TITLE
PyTorch exp error

### ISSUE THREAD

**Issue by nparkstar** [IntelAI/nauta#35]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

I run as below.
nctl experiment submit --name pytorch --template pytorch-training examples/pytorch_mnist.py

result -> FAILED
error log : some line
2020-02-25T08:12:56.333153646+00:00 pytorch-master-0 ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/usr/local/lib/python3.7/site-packages/PIL/__init__.py)

**Cluster configuration details:**
- **Cloud provider or hardware configuration:**
Cluster configuration : my own hardware (3 Inter Servers : 1 master, 2 workers)

- **Operating system:** (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
Centos 7.6
- **Nauta version and commit:** (`nctl version`)(`git rev-parse --short HEAD`):
nctl version`
| Component        | Version                  |
|------------------+--------------------------|
| nctl application | 1.0.0-oss-20202124062154 |
| nauta platform   | 1.0.0-oss-20200221134229 |

all logs -------------
2020-02-25T08:12:56.333059496+00:00 pytorch-master-0   File "pytorch_mnist.py", line 35, in <module>
2020-02-25T08:12:56.333084761+00:00 pytorch-master-0     from torchvision import datasets
2020-02-25T08:12:56.333076341+00:00 pytorch-master-0   File "/usr/local/lib/python3.7/site-packages/torchvision/__init__.py", line 2, in <module>
2020-02-25T08:12:56.333120635+00:00 pytorch-master-0     from .transforms import *
2020-02-25T08:12:56.333090521+00:00 pytorch-master-0   File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
2020-02-25T08:12:56.333097216+00:00 pytorch-master-0     from .fakedata import FakeData
2020-02-25T08:12:56.333102754+00:00 pytorch-master-0   File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
2020-02-25T08:12:56.333126129+00:00 pytorch-master-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
2020-02-25T08:12:56.333153646+00:00 pytorch-master-0 ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/usr/local/lib/python3.7/site-packages/PIL/__init__.py)
2020-02-25T08:12:56.333114393+00:00 pytorch-master-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
2020-02-25T08:12:56.333132536+00:00 pytorch-master-0     from . import functional as F
2020-02-25T08:12:56.333138002+00:00 pytorch-master-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
2020-02-25T08:12:56.333147806+00:00 pytorch-master-0     from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
2020-02-25T08:12:56.333006084+00:00 pytorch-master-0 Traceback (most recent call last):
2020-02-25T08:12:56.333069922+00:00 pytorch-master-0     from torchvision import datasets, transforms
2020-02-25T08:12:56.333108868+00:00 pytorch-master-0     from .. import transforms
2020-02-25T08:13:29.401626054+00:00 pytorch-worker-0     from torchvision import datasets, transforms
2020-02-25T08:13:29.401661965+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/__init__.py", line 2, in <module>
2020-02-25T08:13:29.401680845+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
2020-02-25T08:13:29.401687445+00:00 pytorch-worker-0     from .fakedata import FakeData
2020-02-25T08:13:29.401693211+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
2020-02-25T08:13:29.401699300+00:00 pytorch-worker-0     from .. import transforms
2020-02-25T08:13:29.401723131+00:00 pytorch-worker-0     from . import functional as F
2020-02-25T08:13:29.401728640+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
2020-02-25T08:13:29.401738629+00:00 pytorch-worker-0     from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
2020-02-25T08:13:29.401559390+00:00 pytorch-worker-0 Traceback (most recent call last):
2020-02-25T08:13:29.401704839+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
2020-02-25T08:13:29.401674500+00:00 pytorch-worker-0     from torchvision import datasets
2020-02-25T08:13:29.401615053+00:00 pytorch-worker-0   File "pytorch_mnist.py", line 35, in <module>
2020-02-25T08:13:29.401711254+00:00 pytorch-worker-0     from .transforms import *
2020-02-25T08:13:29.401716654+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
2020-02-25T08:13:29.401744333+00:00 pytorch-worker-0 ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/usr/local/lib/python3.7/site-packages/PIL/__init__.py)
2020-02-25T08:14:52.010687437+00:00 pytorch-worker-0 Traceback (most recent call last):
2020-02-25T08:14:52.010757927+00:00 pytorch-worker-0     from torchvision import datasets
2020-02-25T08:14:52.010761921+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
2020-02-25T08:14:52.010773894+00:00 pytorch-worker-0     from .. import transforms
2020-02-25T08:14:52.010804013+00:00 pytorch-worker-0 ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/usr/local/lib/python3.7/site-packages/PIL/__init__.py)
2020-02-25T08:14:52.010747250+00:00 pytorch-worker-0     from torchvision import datasets, transforms
2020-02-25T08:14:52.010751768+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/__init__.py", line 2, in <module>
2020-02-25T08:14:52.010769767+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
2020-02-25T08:14:52.010785577+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
2020-02-25T08:14:52.010796009+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
2020-02-25T08:14:52.010777597+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
2020-02-25T08:14:52.010781893+00:00 pytorch-worker-0     from .transforms import *
2020-02-25T08:14:52.010800159+00:00 pytorch-worker-0     from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
2020-02-25T08:14:52.010738929+00:00 pytorch-worker-0   File "pytorch_mnist.py", line 35, in <module>
2020-02-25T08:14:52.010766179+00:00 pytorch-worker-0     from .fakedata import FakeData
2020-02-25T08:14:52.010792184+00:00 pytorch-worker-0     from . import functional as F
2020-02-25T08:16:22.039446452+00:00 pytorch-worker-0 Traceback (most recent call last):
2020-02-25T08:16:22.039484524+00:00 pytorch-worker-0   File "pytorch_mnist.py", line 35, in <module>
2020-02-25T08:16:22.039508699+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
2020-02-25T08:16:22.039540319+00:00 pytorch-worker-0     from . import functional as F
2020-02-25T08:16:22.039578586+00:00 pytorch-worker-0     from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
2020-02-25T08:16:22.039516896+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
2020-02-25T08:16:22.039524169+00:00 pytorch-worker-0     from .. import transforms
2020-02-25T08:16:22.039504000+00:00 pytorch-worker-0     from torchvision import datasets
2020-02-25T08:16:22.039528168+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
2020-02-25T08:16:22.039532424+00:00 pytorch-worker-0     from .transforms import *
2020-02-25T08:16:22.039544224+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/functional.py", line 5, in <module>
2020-02-25T08:16:22.039495964+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/__init__.py", line 2, in <module>
2020-02-25T08:16:22.039595337+00:00 pytorch-worker-0 ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (/usr/local/lib/python3.7/site-packages/PIL/__init__.py)
2020-02-25T08:16:22.039491749+00:00 pytorch-worker-0     from torchvision import datasets, transforms
2020-02-25T08:16:22.039513205+00:00 pytorch-worker-0     from .fakedata import FakeData
2020-02-25T08:16:22.039536067+00:00 pytorch-worker-0   File "/usr/local/lib/python3.7/site-packages/torchvision/transforms/transforms.py", line 17, in <module>

**Comment by mateusz-ciesielski** [comment]
Root cause of this problem is described here:
https://github.com/pytorch/vision/issues/1712

I'll prepare a PR to fix this on Nauta's side, meanwhile you can mitigate this issue by creating a requirements.txt file for your experiment and putting following line there:
```
pillow<7
``` 
Then instead of running:
```
nctl experiment submit --name pytorch --template pytorch-training examples/pytorch_mnist.py
```
execute:
```
nctl experiment submit --name pytorch --template pytorch-training --requirements <path to your requirements.txt file> examples/pytorch_mnist.py
```

**Comment by nparkstar** [comment]
Thanks a lot, I will try it.

**Comment by nparkstar** [comment]
I tried as you say, but I don't think it works well.
status is 'QUEUED', and won't be changed.
I am trying to test other features mainly tensorflow.
PyTorch is not important for me now.
Thanks anyway.

**Comment by mateusz-ciesielski** [comment]
You can get more details about experiments in queued state by running:
```
nctl experiment view <experiment name>
```
(if you don't remember name of that particular experiment it will be visible in the output of `nctl experiment list`).

Could you post the output of `experiment view` command here?

**Comment by mateusz-ciesielski** [comment]
Most common cause of experiments being stuck in queued state is misconfiguration of requested cpu/memory resources, if you will see messages like `not enough cpu` or `not enough memory` in the output of `experiment view` you can set default values for cpu/memory requests by using `nctl config` command (https://intelai.github.io/nauta/user-guide/actions/config.html) or by passing `--p cpu` and `-p memory` flags to the `nctl experiment submit` command.

**Comment by nparkstar** [comment]
You are right.
"nctl exp view " show me the message that resource is not enough.

Thank you very much.
